//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrownBagService.DataAccess.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPassword
    {
        public int Id { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public string Password { get; set; }
        public Nullable<int> PasswordFormatId { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
    }
}
