//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrownBagService.DataAccess.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRole
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> FreeShipping { get; set; }
        public Nullable<int> TaxExempt { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> IsSystemRole { get; set; }
        public string SystemName { get; set; }
        public Nullable<int> EnablePasswordLifetime { get; set; }
        public Nullable<int> OverrideTaxDisplayType { get; set; }
        public Nullable<int> DefaultTaxDisplayTypeId { get; set; }
        public Nullable<int> PurchasedWithProductId { get; set; }
    }
}
