//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrownBagService.DataAccess.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expert
    {
        public int Id { get; set; }
        public string Heading { get; set; }
        public string Title { get; set; }
        public string Expert1 { get; set; }
        public string Description { get; set; }
        public string Since { get; set; }
        public string Email { get; set; }
        public string Location { get; set; }
        public string ExpertImage { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }
    }
}
