//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrownBagService.DataAccess.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public int Id { get; set; }
        public string PrimaryCategory { get; set; }
        public Nullable<int> RootCategory { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Artists { get; set; }
        public Nullable<int> Manufacturer { get; set; }
        public Nullable<int> Vendors { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }
    }
}
