//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrownBagService.DataAccess.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int Id { get; set; }
        public string OrderItemGuid { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPriceInclTax { get; set; }
        public Nullable<decimal> UnitPriceExclTax { get; set; }
        public Nullable<decimal> PriceInclTax { get; set; }
        public Nullable<decimal> PriceExclTax { get; set; }
        public Nullable<decimal> DiscountAmountInclTax { get; set; }
        public Nullable<decimal> DiscountAmountExclTax { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }
    }
}
