//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrownBagService.DataAccess.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<System.Guid> OrderGUID { get; set; }
        public string CustomerGUID { get; set; }
        public string CustomerIP { get; set; }
        public Nullable<int> BillingAddressID { get; set; }
        public Nullable<int> ShippingAddressID { get; set; }
        public Nullable<int> PickupAddressID { get; set; }
        public Nullable<int> OrderStatusId { get; set; }
        public Nullable<int> ShippingStatusId { get; set; }
        public string PaymentMethod { get; set; }
        public string CustomerCurrencyCode { get; set; }
        public string TAXIDNumber { get; set; }
        public Nullable<decimal> OrderSubtotalInclTax { get; set; }
        public Nullable<decimal> OrderSubtotalExclTax { get; set; }
        public Nullable<decimal> OrderDiscount { get; set; }
        public Nullable<decimal> OrderShippingCharge { get; set; }
        public Nullable<decimal> PaymentMethodAdditionalFee { get; set; }
        public Nullable<decimal> TaxRates { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public Nullable<decimal> RefundedAmount { get; set; }
        public Nullable<int> RewardPointsHistoryEntryId { get; set; }
        public Nullable<int> AllowStoringCreditCardNumber { get; set; }
        public string CardType { get; set; }
        public string BankName { get; set; }
        public string CardNumber { get; set; }
        public string CardCvv2 { get; set; }
        public string CardExpirationMonth { get; set; }
        public string CardExpirationYear { get; set; }
        public string AuthorizationTransactionId { get; set; }
        public string AuthorizationTransactionCode { get; set; }
        public string AuthorizationTransactionResult { get; set; }
        public string CaptureTransactionId { get; set; }
        public string CaptureTransactionResult { get; set; }
        public string RefNumber { get; set; }
        public Nullable<System.DateTime> PaidDateUtc { get; set; }
        public string ShippingMethod { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }
    }
}
