//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrownBagService.DataAccess.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtpDetail
    {
        public int Id { get; set; }
        public System.Guid RefCustomerGuid { get; set; }
        public string Email { get; set; }
        public string OTP { get; set; }
        public bool IsActive { get; set; }
        public bool IsVerified { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string Prupose { get; set; }
    }
}
