//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrownBagService.DataAccess.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public Nullable<int> Published { get; set; }
        public Nullable<decimal> CP_INR { get; set; }
        public Nullable<decimal> CP_USD { get; set; }
        public Nullable<decimal> CP_Euro { get; set; }
        public Nullable<decimal> CP_GBP { get; set; }
        public Nullable<decimal> OP_INR { get; set; }
        public Nullable<decimal> OP_USD { get; set; }
        public Nullable<decimal> OP_Euro { get; set; }
        public Nullable<decimal> OP_GBP { get; set; }
        public Nullable<decimal> PC_INR { get; set; }
        public Nullable<decimal> PC_USD { get; set; }
        public Nullable<decimal> PC_Euro { get; set; }
        public Nullable<decimal> PC_GBP { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> TaxCategoryId { get; set; }
        public Nullable<int> OrderMinimumQuantity { get; set; }
        public Nullable<int> OrderMaximumQuantity { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> NotReturnable { get; set; }
        public Nullable<int> IsGiftCard { get; set; }
        public Nullable<int> IsRental { get; set; }
        public Nullable<int> MarkAsNew { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> UpdatedOnUtc { get; set; }
    }
}
