//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrownBagService.DataAccess.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<double> Rating1 { get; set; }
        public string ReviewTitle { get; set; }
        public string Review { get; set; }
        public Nullable<int> LikeCount { get; set; }
        public Nullable<int> DislikeCount { get; set; }
        public Nullable<int> ReviewStatus { get; set; }
        public Nullable<System.DateTime> CreatedOnUTC { get; set; }
    }
}
