//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrownBagService.DataAccess.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int Id { get; set; }
        public string VendorName { get; set; }
        public string VendorEmail { get; set; }
        public string Description { get; set; }
        public string PictureURL { get; set; }
        public string VendorAddress { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
    }
}
